### ISSUE TITLE
0.6.3 fails with missing arg

### ISSUE THREAD

**Issue by joshmoore** [ome/omego#109]
```
bash-4.2$ ../omego/bin/omego upgrade --no-start --sym=OMERO.web OMERO.server-5.3.2-314-7e10599-ice36-b88
2017-07-07 09:50:13,059 [omego.upgrad] WARNI "omero upgrade" is deprecated, use "omego install --upgrade"
2017-07-07 09:50:13,059 [omego.upgrad] INFO  UnixInstall: upgrade
2017-07-07 09:50:13,059 [omego.upgrad] INFO  Upgrading OMERO.server-5.3.2-314-7e10599-ice36-b88 (OMERO.web)...
2017-07-07 09:50:13,591 [omego.extern] ERROR Failed to load environment variables from OMERO.web/omero.envvars: [Errno 2] No such file or directory: 'OMERO.web/omero.envvars'
2017-07-07 09:50:13,592 [omego.upgrad] INFO  Stopping server
2017-07-07 09:50:13,592 [omego.extern] INFO  Running [old environment]: admin status --nodeonly
2017-07-07 09:50:13,592 [omego.extern] INFO  Executing [custom environment]: omero admin status --nodeonly
2017-07-07 09:50:14,322 [omego.extern] ERROR Failed [0.730 s]
2017-07-07 09:50:14,322 [omego.upgrad] ERROR Error whilst stopping server: Non-zero return code
command: omero admin status --nodeonly
return code: 62
stdout:
stderr: Missing internal configuration. Run bin/omero admin rewrite.

2017-07-07 09:50:14,322 [omego.upgrad] INFO  Stopping web
2017-07-07 09:50:14,322 [omego.extern] INFO  Running [old environment]: web stop
2017-07-07 09:50:14,322 [omego.extern] INFO  Executing [custom environment]: omero web stop
2017-07-07 09:50:15,069 [omego.extern] ERROR Failed [0.747 s]
2017-07-07 09:50:15,069 [omego.upgrad] ERROR Error whilst stopping web: Non-zero return code
command: omero web stop
return code: 169
stdout:
stderr: ERROR: Django not installed!

2017-07-07 09:50:15,070 [omego.upgrad] INFO  Copying old configuration from OMERO.web/etc/grid/config.xml
2017-07-07 09:50:15,070 [omego.upgrad] WARNI Upgraded server was the same, not deleting
Traceback (most recent call last):
  File "../omego/bin/omego", line 9, in <module>
    load_entry_point('omego==0.6.3', 'console_scripts', 'omego')()
  File "/opt/omero/omego/lib/python2.7/site-packages/omego/main.py", line 52, in entry_point
    (Version.NAME, Version)])
  File "/opt/omero/omego/lib/python2.7/site-packages/yaclifw/framework.py", line 197, in main
    ns.func(ns)
  File "/opt/omero/omego/lib/python2.7/site-packages/omego/upgrade.py", line 526, in __call__
    UnixInstall(self.NAME, args)
  File "/opt/omero/omego/lib/python2.7/site-packages/omego/upgrade.py", line 70, in __init__
    self.handle_database()
  File "/opt/omero/omego/lib/python2.7/site-packages/omego/upgrade.py", line 272, in handle_database
    if self.args.initdb or self.args.upgradedb:
AttributeError: 'Namespace' object has no attribute 'initdb'
bash-4.2$ ../omego/bin/pip freeze | grep omego
omego==0.6.3
```

**Comment by manics** [comment]
I assume this is fixed?
